version: "3.3"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./volumes/mosquitto:/etc/mosquitto
      - ./config/mosquitto/passwd:/etc/mosquitto/passwd
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - internal
  # Database
  database:
    image: timescale/timescaledb:latest-pg15
    container_name: database
    restart: unless-stopped
    env_file: docker-compose.env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    networks:
      - internal
networks:
  internal:
