---
api:
  insecure: true

global:
  checkNewVersion: true
  sendAnonymousUsage: false

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
#    http:
#      redirections:
#        entryPoint:
#          to: websecure
#          scheme: https
  websecure:
    address: :443
  # Mosquitto related exposure
  mqtt:
    address: :1883
#    http:
#      tls:
#        certresolver: myresolver

# -- Configure your CertificateResolver here...
certificatesResolvers:
  myresolver:
    acme:
      tlschallenge: true
      email: youremail@email.com  # <-- Change this to your email
      storage: /var/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entrypoint: web

providers:
  docker:
    exposedByDefault: false
    network: internal
